---
title: "Tidyquiz"
subtitle: "By [Matt Dray](https://twitter.com/mattdray)"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE, context="setup"}
# Set chunk options
knitr::opts_chunk$set(echo = FALSE)

# Get packages
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(learnr))
suppressPackageStartupMessages(library(pacman))
suppressPackageStartupMessages(library(shiny))

# Character vector of tidyverse package names (and try to protect from rogue
# characters in package name; happened with readxl)
tidy_pkgs <- tidyverse_packages() %>%  # calls character vector
  str_replace("\n", "") %>%  # remove newline
  str_replace(">=", "") %>%  # remove greater than or equal to
  str_replace("[:punct:]", "")  # remove punctuation
  
# Install and load full set of tidyverse packages
# (character.only to read elements of character vector, not object name)
p_load(char = tidy_pkgs, character.only = TRUE)

# Tibble where each row is a package-function combination
tidy_funs <-
  tidy_pkgs %>% 
  enframe(name = NULL, value = "package") %>% 
  mutate(functions = map(package, ~p_functions(.x, character.only = TRUE))) %>% 
  unnest()
```

<br>

Can you select the correct package for the named tidyverse function? Made with [{learnr}](https://rstudio.github.io/learnr/), the [tidyverse](https://www.tidyverse.org/) and [{pacman}](https://cran.r-project.org/web/packages/pacman/index.html).

Generate a random question by setting a seed value and pressing 'Go'. Use this seed again to retrieve the same question.

For a new question, click 'Start Over' in the menu pane, select a new seed value and hit 'Go'.

```{r, button, echo=FALSE}
# This chunk contains a Shiny action button
# Set a seed value to 'control the randomness' of sampling functions/packages
# Click the button to apply the value to set.seed()

numericInput("n", "Set seed:", value = 1337)
actionButton("goButton", "Go")
```

```{r, server, context="server"}
# This chunk attempts to builds the text output that can be passed later to the
# quiz() and answer() functions

# Get function name for subject of question

fun_name <- eventReactive(
  input$goButton,
  { 
    set.seed(input$n)  # user-selected value is seed value
    fun_sample <- sample_n(tidy_funs, 1)  # random row from package-functions tibble
    fun_name <- select(fun_sample, functions) %>% pull()  # just the function name
    return(fun_name)
  }
)
output$fun_name_out <- renderText({
  paste0("The function `", fun_name(), "` is from which tidyverse package?")
})

# Get correct answer

ans_correct <- eventReactive(
  input$goButton,
  { 
    set.seed(input$n)  # same seed value as above
    fun_sample <- sample_n(tidy_funs, 1)  # same row as for fun_name as above
    ans_correct <- select(fun_sample, package) %>% pull()  # now take package name
    return(ans_correct)
  }
)
output$ans_correct_out <- renderText({ paste0("{", ans_correct(), "}") })

# Get wrong answer 1 of 3
ans_wrong1 <- eventReactive(
  input$goButton,
  { 
    # Recreate ans_correct so we don't set it as a wrong answer as well
    set.seed(input$n)
    fun_sample <- sample_n(tidy_funs, 1)
    fun_name <- select(fun_sample, functions) %>% pull()
    ans_correct <- select(fun_sample, package) %>% pull()
    # Also get packages that have a function with the same name as ans_correct
    # so we don't see these as a wrong answer as well
    dup_lookup <-  filter(tidy_funs, functions == fun_name) %>% pull(package)
    # Slightly alter the seed to generate a wrong answer
    set.seed(input$n+1)
    ans_wrong1 <- tidy_funs %>%
      distinct(package) %>%  # get unique packages
      filter(!package %in% c(dup_lookup)) %>%  # ignore packages with ans_correct
      sample_n(1) %>%  # choose a remaining package name at random
      pull()  # to character
    return(ans_wrong1)
  }
)
output$ans_wrong1_out <- renderText({ paste0("{", ans_wrong1(), "}") })

# Get wrong answer 2 of 3
# Code as for wrong answer 1, but seed different

ans_wrong2 <- eventReactive(
  input$goButton,
  { 
    set.seed(input$n)
    fun_sample <- sample_n(tidy_funs, 1)
    fun_name <- select(fun_sample, functions) %>% pull()
    ans_correct <- fun_sample %>% select(package) %>% pull()
    dup_lookup <- tidy_funs %>% 
      filter(functions == fun_name) %>% 
      pull(package)
    set.seed(input$n + 2)  # needs to be a different seed to ans_wrong1
    ans_wrong2 <- tidy_funs %>%
      distinct(package) %>%
      filter(!package %in% c(dup_lookup)) %>%  # Also want to exclude ans_wrong1
      sample_n(1) %>% 
      pull()
    return(ans_wrong2)
  }
)
output$ans_wrong2_out <- renderText({ paste0("{", ans_wrong2(), "}") })

# Get wrong answer 3 of 3
# Code as for wrong answers 1 and 2 above, but seed different

ans_wrong3 <- eventReactive(
  input$goButton,
  { 
    set.seed(input$n)
    fun_sample <- sample_n(tidy_funs, 1)
    fun_name <- select(fun_sample, functions) %>% pull()
    ans_correct <- fun_sample %>% select(package) %>% pull()
    dup_lookup <- tidy_funs %>% 
      filter(functions == fun_name) %>% 
      pull(package)
    set.seed(input$n + 3)  # needs to be a different seed to ans_wrong1
    ans_wrong3 <- tidy_funs %>%
      distinct(package) %>%
      filter(!package %in% c(dup_lookup)) %>%  # Also want to exclude ans_wrong1 and ans_wrong2
      sample_n(1) %>%
      pull()
    return(ans_wrong3)
  }
)
output$ans_wrong3_out <- renderText({ paste0("{", ans_wrong3(), "}") })
```

```{r, q1}
quiz(
  caption = "Question ",
  question(
    text = as.character(textOutput("fun_name_out")),
    answer(as.character(textOutput("ans_correct_out")), correct = TRUE),
    answer(as.character(textOutput("ans_wrong1_out"))),
    answer(as.character(textOutput("ans_wrong2_out"))),
    answer(as.character(textOutput("ans_wrong3_out"))),
    random_answer_order = TRUE
  )
)
```
